BACKTEST_CONFIG = {
    "freq": "60min",
    "limit_threshold": None,
    "deal_price": "close",
    "open_cost": 0.0004,
    "close_cost": 0.0004,
    "min_cost": 0,
    "slippage": 0.0001,
    "pos_type": "Position",
    "account": 100000,
    "benchmark": "btcusdt",
    "long_percentile": 0.85,
    "short_percentile": 0.15,
    "rolling_window": 720,
    "position_ratio": 0.95,
}
