LGBM_CONFIG = {
    "loss": "mse",
    "objective": "huber",
    "alpha": 0.95,
    "learning_rate": 0.015,
    "num_boost_round": 500,
    "early_stopping_rounds": 50,
    "num_leaves": 31,
    "max_depth": 6,
    "min_data_in_leaf": 100,
    "min_child_weight": 0.001,
    "lambda_l1": 0.5,
    "lambda_l2": 1.5,
    "min_gain_to_split": 0.01,
    "subsample": 0.7,
    "subsample_freq": 1,
    "colsample_bytree": 0.7,
    "colsample_bynode": 0.7,
    "num_threads": 8,
    "verbosity": -1,
    "seed": 42,
}